<?php
/**
 * Shipper HQ
 *
 * @category ShipperHQ
 * @package ShipperHQ_UPSMyChoice
 * @copyright Copyright (c) 2021 Zowta LTD and Zowta LLC (http://www.ShipperHQ.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author ShipperHQ Team sales@shipperhq.com
 */

/** @var ShipperHQ\UPSMyChoice\Block\Frontend\Checkout\UPSMyChoice\Renderer $block */
?>
<upsmychoiceenrollmentapp></upsmychoiceenrollmentapp>
<script>
    const settings = <?= /* @noEscape */ $block->getSettingsAsJson(); ?>;
    if (settings.eligible) {
        require([settings.jsBundleUrl], (bundle) => {
            const domNode = document.querySelector('upsmychoiceenrollmentapp')
            const {enrollmentUrl} = settings;
            bundle.renderApp(domNode, {enrollmentUrl})
        })
    }
</script>
